# Generated by Django 3.0.6 on 2020-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblAllProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=300)),
                ('Duration', models.IntegerField()),
                ('ProjectManager', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
