# Generated by Django 3.0.6 on 2020-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_tblallproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblTaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=300)),
                ('ProjectID', models.IntegerField()),
                ('startDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Description', models.CharField(max_length=500)),
                ('Assignee', models.CharField(max_length=100)),
            ],
        ),
    ]
